### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by flamewing** [grahambates/68kcounter-vscode#1]
I created a [large file](https://gist.github.com/flamewing/73973a94eaf3d24197db5e1080c6a56e) for testing this extension. It contains every instruction and addressing mode from the original MC68000, as well as cycle counts obtained from [the file](https://gist.github.com/flamewing/af3b0863570afe317518eff849f58689) I mentioned in another issue.

Toggling cycle counts for this file takes 20+ seconds on my computer; I can assemble this file over 200 times on the same computer in these 20 seconds. Using the web version of grahambates/68kcounter is almost instant, meaning this is probably on the gutter drawing code on this extension.

**Comment by grahambates** [comment]
Yeah I'm pretty sure it's VS Code actually updating the annotations which is the bottleneck. I already optimise to only update lines that have changed, but I'm not sure there's too much that can be done about the initial render.

To be honest the whole approach of prefixing lines using the `before` property feels like a bit of a hack, but it's how other extensions seem to do this e.g. Git Lens. I'll have another look into alternative approaches.

**Comment by flamewing** [comment]
Strange; testing over Git Lens, it takes a couple seconds to do a full git blame annotation on a file with 25k lines, while the 68kcounter takes 14 seconds to do the same. How do they manage to do it so fast?

**Comment by grahambates** [comment]
Just spent some time looking into this. It's because I'm definining a separate decorator per line, whereas Git Lens applies a single decorator (e.g. for a single commit message) to multiple.

I was able to get the annotations to display _much_ quicker by grouping them by text value. I can define and apply a single decorator for all lines with the timing `4(1/0)` for example. Unfortunately this breaks the ability to do partial updates to modified lines using the existing method, so I need to rethink the approach a bit. It does look promising though so hopefully I'll have something working soon.

**Comment by grahambates** [comment]
I found a better way to do this. I was able to use a single decorator type across all lines in the file and change the string values and colours per line through the `renderOptions` argument. Using this the performance seems good enough that we don't need to worry about partial updates.

This fix is included in the latest relase.

**Comment by flamewing** [comment]
An alternative to investigate is to maybe create a decorator for every (say) 1000 lines to allow for partial updates and still keep a fast speed. Though to be fair, if a file is large enough that it needs this kind of thing to make usable, it is probably too large and should be split into multiple files.

**Comment by grahambates** [comment]
Yeah that's worth investigating, I'll give it a try and see how much I can improve things.

I've been trying out the new implementation on large files. One really huge one I've found in the wild is on [Trash'm Pro](https://github.com/bsdf/TRASHM-PRO) which has a [~64kloc file](https://github.com/bsdf/TRASHM-PRO/blob/main/trash.s )! One this example it takes just over a second to toggle annotations which is pretty good all things considered, but not usable for realtime editing.

I'm thinking of setting a threshold where realtime updates are disabled and annotations are toggled off on change. I think this is reasonable and I can recall other examples of extensions that disable features on very large files.

Another challenge is that it's no longer possible to reliably parse isolated lines of code now that the parser takes into account things like constants and macros elsewhere in the file. This means that currently the parser needs to reprocess the whole file and not just the updated lines. On the Trash'm Pro example this alone takes around 400ms. This could be addressed by introducing caching logic into the parser, which is something I'm going to investigate too.
