### ISSUE TITLE
Duplicated gutter

### ISSUE THREAD

**Issue by flamewing** [grahambates/68kcounter-vscode#2]
If you toggle counts, swap to another file (split vertically or horizontally), then swap back to the file with counts enabled, the gutter showing the size/cycles will be duplicated:
![image](https://user-images.githubusercontent.com/6319024/119706703-9a4cf180-be5a-11eb-9749-aca96393114a.png)

This can be highly annoying due to issue #1 on all but the smallest files because the two gutters will combine to further slow down vscode.

**Comment by grahambates** [comment]
This is no longer occurring in the new implementation.
